version: "3.1"

services:
  prometheus:
    image: prom/prometheus:v2.50.1
    restart: always
    ports:
      - 9091:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./consoles:/etc/prometheus/consoles
