on: [push, pull_request]
name: Test Go
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.25.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@def8c394e3ad351a79bc93815e4a585520fe993b # v6.2.0
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - run: go test -race -covermode=atomic -coverprofile=coverage.out ./...
    - uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
