on: [push, pull_request]
name: Test Go
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@6f26dcc668f723b50085562b23062c5a4be16a3d # v5.2.0
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - run: go test -race -covermode=atomic -coverprofile=coverage.out ./...
    - uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
